name: matrix
on:
  push
jobs:
  matrix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
      echo ${{ matrix.os }}