name: platform

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  environment:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}    
    steps:
    - name: infomation
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: apt update
      run: sudo apt-get update
    
    - name: create build environment
      run: |
        sudo apt-get install gcc-multilib g++-multilib
        cmake -E make_directory ${{runner.workspace}}/x32
        cmake -E make_directory ${{runner.workspace}}/x64
    
    - name: config x32
      env:
        CC: gcc
        CXX: g++
        CXXFLAGS: -m32
      shell: bash
      working-directory: ${{runner.workspace}}/x32
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    
    - name: build x32
      working-directory: ${{runner.workspace}}/x32
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -j 2

    - name: config x64
      env:
        CC: gcc
        CXX: g++
        CXXFLAGS: -m64
      shell: bash
      working-directory: ${{runner.workspace}}/x64
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    
    - name: build x64
      working-directory: ${{runner.workspace}}/x64
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -j 2

  clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: apt update
      run: |
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib

    - name: x32
      run: |
        mkdir x32 && cd x32
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCXXFLAGS="-m32" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_SYSTEM_PROCESSOR=x86 ..
        cmake --build . --config $BUILD_TYPE -j 2
    
    - name: x64
      run: |
        mkdir x64 && cd x64
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCXXFLAGS="-m64" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_SYSTEM_PROCESSOR=x64 ..
        cmake --build . --config $BUILD_TYPE -j 2

  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ndk-fix-debug
      run: sed -i -e '/^  -g$/d' $ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
    - name: arm32
      run: |
        mkdir arm32 && cd arm32
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-21 ..
        cmake --build . -j 2
    - name: arm64
      run: |
        mkdir arm64 && cd arm64
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_ABI="arm64-v8a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-21 ..        
        cmake --build . -j 2
        
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: x86
      run: |
        mkdir x86; cd x86
        cmake -T v142,host=x64 -A Win32 ..
        cmake --build . --config Release -j 2
    - name: x64
      run: |
        mkdir x64; cd x64
        cmake ..
        cmake --build . --config Release -j 2
      