# name: transfer

# on: 
  # push

# jobs:
  # transfer:
    # https://github.com/marketplace/actions/scp-command-to-transfer-files
    # needs: [gcc, clang, android, windows]
    # name: copy build library to me
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@master
      # - name: copy file via ssh password
        # uses: appleboy/scp-action@master
        # with:
          # host: ${{ secrets._HOST_ADDRESS }}
          # username: ${{ secrets._SSH_USERNAME }}
          # password: ${{ secrets._SSH_PASSWORD }}
          # port: ${{ secrets._SSH_PORT }}
          # source: "${{ secrets._TO_CPOY }}"
          # target: "${{ secrets._CPOY_TO }}"